name: Deploy Spiderman WebApp

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node (requerido por Pages, aunque no uses Node.js)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload GitHub Pages artifact
        run: |
          mkdir public
          cp index.html style.css script.js public/
          cp -r assets public/assets

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2